[colors.primary]
background = "#282828"
foreground = "#fbf1c7"

[colors.normal]
black = "#282828"   # 40-40-40
red = "#cc241d"     # 204-36-29
green = "#98971a"   # 152-151-26
yellow = "#d79921"  # 215-153-33
blue = "#458588"    # 69-133-136
magenta = "#b16286" # 177-98-134
cyan = "#689d6a"    # 104-157-106
white = "#928374"   # 146-131-116

[colors.bright]
black = "#928374"   # 146-131-1160
red = "#fb4934"     # 251-73-52
green = "#b8bb26"   # 184-187-38
yellow = "#fabd2f"  # 250-189-47
blue = "#83a598"    # 131-165-152
magenta = "#d3869b" # 211-134-155
cyan = "#8ec07c"    # 142-192-12
white = "#ebdbb2"   # 235-219-1784
